upgrades:
  ONE:
    speed: 8
    price: 50
  TWO:
    speed: 5
    price: 100
  THREE:
    speed: 4
    price: 250
  FOUR:
    speed: 3
    price: 600
  FIVE:
    speed: 2
    price: 1600
  SPECIAL:
    speed: 4
    price: -1


##Use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for item names
crops:
  - WHEAT
  - SEEDS

monsters:
  - ROTTEN_FLESH
  - BONE
  - ARROW

##Please change the appropriate values
sql:
  host: CHANGE-THIS
  port: 3306
  database: CHANGE-THIS
  username: root
  password: CHANGE-THIS
